### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by chnn** [ember-cli/website#1]
Let's continue the discussion from ember-cli/ember-cli#2589 here. 

Some initial topics from @joostdevries:

- What's our starting point? Blank, existing site, my repo from ember-cli/ember-cli#2589
- Build tool? Static site w/ Jekyll, ember, etc.
- Deployment? GitHub Pages?

**Comment by filipelinhares** [comment]
Hey @chnn, do you began to do something? I want to contribute with some projects, If you need any help, let me know.

**Comment by joostdevries** [comment]
@filipelinhares this is now tracked in ember-cli/ember-cli#3307
